let Joi,ref,CustomErrorHandler,User;_d50‍.x([["default",()=>_d50‍.o]]);_d50‍.w("joi",[["default",["Joi"],function(v){Joi=v}],["ref",["ref"],function(v){ref=v}]]);_d50‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);_d50‍.w("../../models",[["User",["User"],function(v){User=v}]]);


const registerController = {
   async register(req, res, next){
        // validation 
        const registeerSchema = Joi.object({
            name : Joi.string().min(3).max(30).required(),
            email :Joi.string().email().required(),
            password : Joi.string().pattern(new RegExp('^[a-zA-Z0-9]{3,30}$')).required(),
            repeat_password : Joi.ref('password')
        });
        _d50‍.g.console.log(req.body);
        const { error } = registeerSchema.validate(req.body);
        if(error){
            return next(error)
        }
        
        //if user already registered then error generate
        try{
            const exist = await User.exists({'email': req.body.email});
            if(exist){
                return next(CustomErrorHandler.alreadyExist('This Email is already Taken'));
            }
        }catch(err){
        return next(err);
        }

  res.json({
      msg : "Hello this is my fist message"
  })
    }
}


_d50‍.d(registerController);





